export const TABLE_REQUEST_LOAD_PAGE = "TABLE_REQUEST_LOAD_PAGE";
export const TABLE_SUCCESSFUL_LOAD_PAGE = "TABLE_SUCCESFUL_LOAD_PAGE";
export const TABLE_UNSUCCESSFUL_LOAD_PAGE = "TABLE_UNSUCCESFUL_LOAD_PAGE";

export const TABLE_REQUEST_ADD_ROW = "TABLE_REQUEST_ADD_ROW";
export const TABLE_SUCCESSFUL_ADD_ROW = "TABLE_SUCCESSFUL_ADD_ROW";
export const TABLE_UNSUCCESSFUL_ADD_ROW = "TABLE_UNSUCCESSFUL_ADD_ROW";

export const TABLE_REQUEST_DELETE_ROW = "TABLE_REQUEST_DELETE_ROW";
export const TABLE_SUCCESSFUL_DELETE_ROW = "TABLE_SUCCESSFUL_DELETE_ROW";
export const TABLE_UNSUCCESSFUL_DELETE_ROW = "TABLE_UNSUCCESSFUL_DELETE_ROW";

export const TABLE_REQUEST_UPDATE_ROW = "TABLE_REQUEST_UPDATE_ROW";
export const TABLE_SUCCESSFUL_UPDATE_ROW = "TABLE_SUCCESSFUL_UPDATE_ROW";
export const TABLE_UNSUCCESSFUL_UPDATE_ROW = "TABLE_UNSUCCESSFUL_UPDATE_ROW";

